###
# @name adminLogin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin@teste.com",
  "password": "123456"
}

###
@tokenAdmin = {{ adminLogin.response.body.accessToken }}

###
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer {{ tokenAdmin }}

{
  "title": "post do admin post ",
  "content": "Conteudo do primeiro post"
}

###
GET http://localhost:3000/posts
Authorization: Bearer {{ tokenAdmin }}
